create database ishu;

use ishu;

create table ishika
(
student_id int primary key,
name varchar(20),
age int CHECK (AGE>=18),
class varchar(25)
);

insert into ishika (student_id,name,age,class)
values
(101,"ISHIKA",20,"BCA"),
(102,"AYUSH",21,"BA"),
(103,"SAKSHAM",15,"DIPLOMA"),
(104,"ANJU",30,"BA"),
(105,"MANOJ",35,"MBA"),
(106,"POOJA",30,"BCA"),
(107,"KITTU",20,"BTECH");


alter table ishika
add email varchar(200);

alter table ishika
modify age int not null;

alter table ishika
drop column email;

drop table course4;

CREATE TABLE course4
(
    course_id INT,
    course_name VARCHAR(50)
);

INSERT INTO course4 (course_id, course_name)
VALUES
(1, 'BCA'),
(2, 'BA'),
(3, 'DIPLOMA'),
(4, 'BA'),
(5, 'MBA'),
(6, 'BCA'),
(7, 'BTECH');

CREATE TABLE enrollment4 (
    enrollment_id INT PRIMARY KEY,
    student_id INT,
    course_id INT,
    FOREIGN KEY (student_id) REFERENCES ishika(student_id),
    FOREIGN KEY (course_id) REFERENCES Course(course_id)
);

select * from enrollment4;

select * from ISHIKA_CHOUDHARY;

select * from course2;

alter table ishika
change column name fullname varchar(50);

update ishika
set age = 21
where student_id=101;

update ishika
set fullname = "ISHIKA CHOUDHARY"
where student_id = 101;

delete from ishika 
where student_id = 106;

rename table ishika to ISHIKA_CHOUDHARY;

ALTER TABLE ISHIKA_CHAUDHARY;

select fullname , age from ISHIKA_CHOUDHARY
where class = "BA";

update ISHIKA_CHOUDHARY
set fullname = "AYUSH DUBEY"
where student_id = 102;

select * from ISHIKA_CHOUDHARY
WHERE (AGE>= 20);

SELECT * FROM ISHIKA_CHOUDHARY
WHERE CLASS = "BTECH";

SELECT * FROM ISHIKA_CHOUDHARY
WHERE AGE >=20
ORDER BY AGE ASC LIMIT 3;

SELECT * FROM ISHIKA_CHOUDHARY
WHERE AGE >=20
ORDER BY AGE DESC LIMIT 3;

SELECT * FROM ISHIKA_CHOUDHARY
WHERE fullname 
like "a%";

SELECT * FROM ISHIKA_CHOUDHARY
WHERE fullname 
like "%a%";

SELECT * FROM ISHIKA_CHOUDHARY
WHERE fullname 
like "%a";

SELECT * FROM ISHIKA_CHOUDHARY
WHERE fullname 
like "_a%";

SELECT * FROM ISHIKA_CHOUDHARY
WHERE fullname 
like "%a_";

SELECT DISTINCT Class FROM ISHIKA_CHOUDHARY;

SELECT * FROM ISHIKA_CHOUDHARY
LIMIT 2;

SELECT DISTINCT Class
FROM ISHIKA_CHOUDHARY
WHERE Age >= 20
ORDER BY Class ASC
LIMIT 4;

ALTER TABLE ISHIKA_CHOUDHARY
ADD COLUMN CITY VARCHAR(100);

UPDATE ISHIKA_CHOUDHARY
SET CITY = "BAGHPAT" 
WHERE student_id = 101;

select * from ISHIKA_CHOUDHARY;

UPDATE ISHIKA_CHOUDHARY
SET CITY = "AYODHA" 
WHERE student_id = 102;

UPDATE ISHIKA_CHOUDHARY
SET CITY = "BAGHPAT" 
WHERE student_id = 103;

UPDATE ISHIKA_CHOUDHARY
SET CITY = "MASSORIE" 
WHERE student_id = 104;

UPDATE ISHIKA_CHOUDHARY
SET CITY = "GHAZIABAD" 
WHERE student_id = 105;

UPDATE ISHIKA_CHOUDHARY
SET CITY = "NOIDA" 
WHERE student_id = 107;

SELECT * FROM ISHIKA_CHOUDHARY
WHERE AGE >20 AND CITY = "BAGHPAT";

SELECT * FROM ISHIKA_CHOUDHARY
WHERE STUDENT_ID = 105 OR CITY = "NOIDA";

SELECT * FROM ISHIKA_CHOUDHARY
WHERE NOT CITY = "BAGHPAT";

SELECT * FROM ISHIKA_CHOUDHARY
WHERE (AGE BETWEEN 15 AND 23)
AND CITY = "BAGHPAT"; 

SELECT * FROM ISHIKA_CHOUDHARY
WHERE AGE BETWEEN 15 AND 23;

SELECT * FROM ISHIKA_CHOUDHARY
WHERE AGE IS NULL;

SELECT * FROM ISHIKA_CHOUDHARY
WHERE AGE IS NOT NULL;

SELECT FULLNAME,AGE,
CASE 
WHEN AGE = 15 THEN "MINOR"
WHEN AGE >= 18 THEN "MAJOR"
END AS NEW_AGE
FROM ISHIKA_CHOUDHARY;

select * from ishika_choudhary
where class in ("BCA","BA","MCA");

SELECT * ,
IF(AGE >=18,"CAN VOTE","CAN'T VOTE") AS NEW_AGE
FROM ISHIKA_CHOUDHARY;

ALTER TABLE ISHIKA_CHOUDHARY
ADD COLUMN SALARY INT;

UPDATE ISHIKA_CHOUDHARY
SET SALARY = 15000
WHERE STUDENT_ID = 101;

UPDATE ISHIKA_CHOUDHARY
SET SALARY = 20000
WHERE STUDENT_ID = 102;

UPDATE ISHIKA_CHOUDHARY
SET SALARY = 10050
WHERE STUDENT_ID = 103;

UPDATE ISHIKA_CHOUDHARY
SET SALARY = 10000
WHERE STUDENT_ID = 104;

UPDATE ISHIKA_CHOUDHARY
SET SALARY = 10800
WHERE STUDENT_ID = 105;

UPDATE ISHIKA_CHOUDHARY
SET SALARY = 12000
WHERE STUDENT_ID = 107;

SELECT * FROM ISHIKA_CHOUDHARY;

SELECT SUM(SALARY) AS SUM_SALARY
FROM ISHIKA_CHOUDHARY;

ALTER TABLE ISHIKA_CHOUDHARY
ADD COLUMN DEPARTMENT VARCHAR(50);

UPDATE ISHIKA_CHOUDHARY
SET DEPARTMENT="DATA ANALYST"
WHERE STUDENT_ID = 101;

UPDATE ISHIKA_CHOUDHARY
SET DEPARTMENT="DATA ANALYST"
WHERE STUDENT_ID = 102;

UPDATE ISHIKA_CHOUDHARY
SET DEPARTMENT="DATA ENTRY"
WHERE STUDENT_ID = 103;

UPDATE ISHIKA_CHOUDHARY
SET DEPARTMENT="ACCOUNTANT"
WHERE STUDENT_ID = 104;

UPDATE ISHIKA_CHOUDHARY
SET DEPARTMENT="TEACHING"
WHERE STUDENT_ID = 105;

UPDATE ISHIKA_CHOUDHARY
SET DEPARTMENT="DATA ENTRY"
WHERE STUDENT_ID = 107;

SELECT * FROM ISHIKA_CHOUDHARY;

ALTER TABLE ISHIKA_CHOUDHARY
RENAME column CLASS TO COURSE;

ALTER TABLE ISHIKA_CHOUDHARY
RENAME TO ISHUU;

SELECT * , 
(SELECT COUNT(STUDENT_ID) FROM ISHU) AS TOTAL
FROM ISHUU;

SELECT * FROM ISHUU;

SELECT SUM(salary) AS total_salary
FROM ISHUU;

SELECT MAX(salary) AS total_salary
FROM ISHUU;

SELECT MIN(salary) AS total_salary
FROM ISHUU;

SELECT AVG(salary) AS total_salary
FROM ISHUU;

SELECT COUNT(salary) AS total_salary
FROM ISHUU;

SELECT *FROM ISHUU;

SELECT DEPARTMENT, AVG(SALARY)
FROM ISHUU
group by DEPARTMENT;

SELECT department, AVG(salary) AS avg_salary
FROM ISHUU
GROUP BY department
HAVING AVG(salary) > 10800;




